version: "3.7"

services:
  peppermint:
    image: pepperlabs/peppermint:latest
    ports:
      - 172.17.0.1:32769:3000
      - 172.17.0.1:1001:5003
    restart: always
    depends_on:
      - postgres
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      SECRET: ${ADMIN_PASSWORD}
      DATABASE_URL: postgres://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}/${DB_DATABASE} 

  postgres:
    image: elestio/postgres:15
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "172.17.0.1:39530:5432"

  pgadmin4:
    image: elestio/pgadmin:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "172.17.0.1:62762:8080"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
